config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dcnios:
      branch: main
      repo: https://github.com/interTwin-eu/dcnios
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-salmon-gerbil.sh
        container: qc.acc_lousy-firebrick-kangaroo
  QC.Doc:
    repos:
      github.com/interTwin-eu/dcnios find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-maroon-dingo.sh
        container: qc.doc_shaky-black-bordeaux
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cyan-hamster.sh
        container: qc.doc_whiny-denim-barb
  QC.Lic:
    repos:
      github.com/interTwin-eu/dcnios licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-mauve-mayfly.sh
        container: qc.lic_homely-gold-snail
  QC.Ver:
    repos:
      github.com/interTwin-eu/dcnios get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cobalt-eagle.sh
        container: qc.ver_snippy-grey-caracal
timeout: 5400
