config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dcnios:
      branch: dev-slangarita
      repo: https://github.com/interTwin-eu/dcnios
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-periwinkle-gar.sh
        container: qc.acc_sleazy-buff-wolf
  QC.Doc:
    repos:
      github.com/interTwin-eu/dcnios find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-amber-mule.sh
        container: qc.doc_sickly-wisteria-seal
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-goldenrod-spider.sh
        container: qc.doc_greasy-chocolate-gopher
  QC.Lic:
    repos:
      github.com/interTwin-eu/dcnios licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-saffron-eleuth.sh
        container: qc.lic_baggy-bistre-quetzal
  QC.Ver:
    repos:
      github.com/interTwin-eu/dcnios get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-crimson-dingo.sh
        container: qc.ver_goopy-scarlet-woodpecker
timeout: 5400
