config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dcnios:
      branch: main
      repo: https://github.com/interTwin-eu/dcnios
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-persimmon-tapir.sh
        container: qc.acc_craggy-cobalt-catfish
  QC.Doc:
    repos:
      github.com/interTwin-eu/dcnios find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-khaki-rabbit.sh
        container: qc.doc_snoopy-purple-catfish
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-lemon-gerbil.sh
        container: qc.doc_wiggy-fuchsia-sheepdog
      github.com/interTwin-eu/dcnios markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-taupe-grasshopper.sh
        container: qc.doc_homely-tomato-spaniel
  QC.Lic:
    repos:
      github.com/interTwin-eu/dcnios licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-chartreuse-crane.sh
        container: qc.lic_cheeky-platinum-iguana
  QC.Sec:
    repos:
      github.com/interTwin-eu/dcnios bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-salmon-raccoon.sh
        container: qc.sec_baggy-carmine-robin
  QC.Sty:
    repos:
      github.com/interTwin-eu/dcnios flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-cobalt-ray.sh
        container: qc.sty_snoopy-goldenrod-ladybird
      github.com/interTwin-eu/dcnios hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cerise-cheetah.sh
        container: qc.sty_shaky-alizarin-goose
      github.com/interTwin-eu/dcnios jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-amethyst-whippet.sh
        container: qc.sty_baggy-goldenrod-shark
  QC.Uni:
    repos:
      github.com/interTwin-eu/dcnios pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-grey-leopard.sh
        container: qc.uni_shabby-orange-dragonfly
  QC.Ver:
    repos:
      github.com/interTwin-eu/dcnios get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-orchid-chimpanzee.sh
        container: qc.ver_jumpy-aquamarine-ragdoll
timeout: 5400
