config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dcnios:
      branch: main
      repo: https://github.com/interTwin-eu/dcnios
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-chartreuse-chow.sh
        container: qc.acc_baggy-turquoise-wombat
  QC.Doc:
    repos:
      github.com/interTwin-eu/dcnios find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-ivory-squirrel.sh
        container: qc.doc_skanky-puce-malamute
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-dandelion-binturong.sh
        container: qc.doc_craggy-sepia-moose
  QC.Lic:
    repos:
      github.com/interTwin-eu/dcnios licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-auburn-budgerigar.sh
        container: qc.lic_blurry-wisteria-barb
  QC.Ver:
    repos:
      github.com/interTwin-eu/dcnios get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-burgundy-cichlid.sh
        container: qc.ver_hilly-asparagus-russel
timeout: 5400
