config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dcnios:
      branch: main
      repo: https://github.com/interTwin-eu/dcnios
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-buff-hare.sh
        container: qc.acc_muggy-razzmatazz-crocodile
  QC.Doc:
    repos:
      github.com/interTwin-eu/dcnios find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cyan-wolfhound.sh
        container: qc.doc_slimy-azure-crane
      github.com/interTwin-eu/dcnios git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-purple-ferret.sh
        container: qc.doc_trippy-denim-kakapo
  QC.Lic:
    repos:
      github.com/interTwin-eu/dcnios licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-amber-caterpillar.sh
        container: qc.lic_greasy-razzmatazz-birman
  QC.Ver:
    repos:
      github.com/interTwin-eu/dcnios get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-orange-orangutan.sh
        container: qc.ver_zippy-indigo-meerkat
timeout: 5400
